version: '3'

services:
  # OpenCrawl API Service
  api:
    build:
      context: ../..
      dockerfile: opencrawl/examples/Dockerfile
    container_name: opencrawl-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/opencrawl
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_TOPIC=pathik_crawl_data
      - PYTHONPATH=/app
      # Explicitly set these to avoid pathik using defaults
      - PATHIK_KAFKA_BROKERS=redpanda:9092
      - PATHIK_BROKER_URL=redpanda:9092
    env_file:
      - .env
    depends_on:
      - postgres
      - redpanda
    networks:
      - opencrawl-network

  # PostgreSQL Database (v17)
  postgres:
    image: postgres:17
    container_name: opencrawl-postgres-api
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: opencrawl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - opencrawl-network

  # Redpanda (Kafka API compatible)
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: opencrawl-redpanda
    ports:
      - "9092:9092"      # Kafka API
      - "9644:9644"      # Redpanda Admin API
    environment:
      REDPANDA_RPC_SERVER_LISTEN_ADDR: 0.0.0.0
      REDPANDA_KAFKA_ADDRESS: 0.0.0.0:9092
      REDPANDA_PANDAPROXY_PANDAPROXY_API_ADDR: 0.0.0.0:8082
      REDPANDA_CONFIG_ORGANIZATION_NAME: opencrawl
      REDPANDA_CONFIG_CLUSTER_NAME: opencrawl-local
      REDPANDA_ADVERTISED_KAFKA_ADDR: redpanda:9092
      REDPANDA_ADMIN_ADVERTISED_SERVER_ADDR: redpanda:9644
      REDPANDA_SEED_SERVERS: "redpanda:33145"
      REDPANDA_DISABLE_METRICS: "true"
      REDPANDA_UNBOUNDED_RETRIES: "false"
      REDPANDA_AUTO_CREATE_TOPICS_ENABLED: "true"
      REDPANDA_CONFIG_SUPERUSERS: "[]"
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
    networks:
      - opencrawl-network

volumes:
  postgres_data:

networks:
  opencrawl-network:
    driver: bridge 